POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ2FtaWwuY29tIiwiZXhwIjoxNzE5MzUzMzQ2LCJ1c2VySWQiOjB9.to2OlJoYKOUOTCj82vYXHMWwc-mpbyyalyhRxWRHlF4

{
    "name": "test event",
    "description": "test Description",
    "location": "test location",
    "dateTime": "2024-06-17T17:44:50.000Z"
}
